name: C++ C CI with Automake

on:
  push:
    branches: [branchAutomake]
  pull_request:
    branches: [branchAutomake]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++

      - name: Generate configuration scripts
        run: |
          autoreconf --install

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Create distribution tarball
        run: make dist

      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: func-dist
          path: func-*.tar.gz
