name: Build Debian Package

on:
  push:
    branches: [branchAutoPackage]
  pull_request:
    branches: [branchAutoPackage]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ dpkg-dev

      - name: Generate configuration scripts
        run: |
          autoreconf --install

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Build .deb package
        run: |
          dpkg-deb --build debian

      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: func-deb-package
          path: debian.deb
