name: Unit Test first

on:
  push:
    branches: [branchHTTPserver]
  pull_request:
    branches: [branchHTTPserver]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libgtest-dev

      - name: Generate configuration and build
        run: |
          autoreconf --install
          ./configure
          make

      - name: Run test
        run: |
          make check
          
          
